language: node_js
node_js:
  - 11
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - sudo dpkg --add-architecture i386
  - wget -qO- https://dl.winehq.org/wine-builds/Release.key | sudo apt-key add -
  - sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ bionic main'
  - sudo apt-get install --install-recommends winehq-stable
addons:
  apt:
    update: true
jobs:
  include:
    - stage: "Verify"
      script: yarn test
    - stage: "Build distributions"
      if: branch = master
      script: yarn build && yarn dist
