language: node_js
node_js:
  - 11
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: "Verify"
      script: yarn test
    - stage: "Build"
      script:
        - yarn install
        - yarn build
    - stage: "Dist"
      script: ./dist.sh
